CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,          
    name VARCHAR(50) NOT NULL,   
    email VARCHAR(100) NOT NULL,    
    password TEXT NOT NULL,   
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);